### ISSUE TITLE
增加echo模式，增加能效比的计算，增加海量连接测试支持

### ISSUE THREAD

**Issue by lesismal** [lxzan/wsbench#1]
多数实际场景中单个连接的数据交互没有那么多，像tcpkali那种一边按照固定频率不停发的方式，如果设置的频率过大就被server限流close了，不符合实际场景。

计算单位cpu、mem消耗对应的吞吐，相当于能效比

海量连接数需要多端口，如果测试client配置低不适合每个连接一个协程

**Comment by lxzan** [comment]
用docker测试海量连接的话不需要多端口；测试“能效比”也需要用docker限制资源

**Comment by lesismal** [comment]
但docker还要把每个client side的数据整合统计，而且多个docker client不同时段发起连接，连接成功后已经开始压测会导致server接受新连接能力下降、很难在压测周期内真正测得预设的连接数情况下数据，所以仍然需要中心化的手段去控制各个client的真正开始发送数据时间。还可能有其他的多client需要整合的细节应该被考虑。
tcpkalli好像难做到这些。

所以这样算下来，分多个docker很麻烦，不如多个端口。

**Comment by lxzan** [comment]
怎么随意指定客户端的ip:port ？

**Comment by lesismal** [comment]
server多启动一组port，client均匀分布就行了

**Comment by lesismal** [comment]
我之前为了测nbio的，server开50个port，比docker、虚拟网络都省事多了：
https://github.com/lesismal/nbio-examples/tree/master/websocket_1m

**Comment by lesismal** [comment]
nbio直接配置Addrs就行了，你们基于标准库的或者gws自己server那个也都容易
https://github.com/lesismal/nbio-examples/blob/master/websocket_1m/server_net/server.go#L43


client如果用基于标准库的，如果是echo模式像gorilla那种允许用户自己ReadMessage还好、少量逻辑协程就可以了，像gws这种只能读协程的资源占用有点太多了，这也是为什么之前我说让你把ReadMessage外放出来允许用户自己处理，不只是容易替换gorilla，还有这个好处

**Comment by lesismal** [comment]
nbio自己的websocket.Dialer是加入到poller里的异步，倒是不占用读写协程，但少量连接的场景吞吐性能不如标准库方案，跟NonBlocking模式的server一样，只是支撑海量连接这种场景优势大

**Comment by lesismal** [comment]
另外就是，go的压测工具本身有可能就是瓶颈，用go client测go server可能还好，但如果用去测c/cpp/rust的可能测不出上限，不如考虑下用rust的websocket试试，前阵子刚好deno那个websocket号称超高性能。性能领域，go跟那几个语言比，还是差一大截

**Comment by lesismal** [comment]
有一些优化点可以考虑，比如发送方如果每次都是相同的数据，第一次encode后就buffer存上，后续每次都conn直接Write这个buffer好了，读的倒是得仔细考虑

**Comment by lxzan** [comment]
> server多启动一组port，client均匀分布就行了

我以为客户端会受到本地端口的数量限制

**Comment by lxzan** [comment]
> 有一些优化点可以考虑，比如发送方如果每次都是相同的数据，第一次encode后就buffer存上，后续每次都conn直接Write这个buffer好了，读的倒是得仔细考虑

我把时间戳追加到尾部了，为了计算延迟

**Comment by lesismal** [comment]
> > 有一些优化点可以考虑，比如发送方如果每次都是相同的数据，第一次encode后就buffer存上，后续每次都conn直接Write这个buffer好了，读的倒是得仔细考虑
> 
> 我把时间戳追加到尾部了，为了计算延迟

每次只改buffer一小部分也比整个从头打包要强

**Comment by lxzan** [comment]
固定某个连接下是只改一小部分, 生成随机数也是有开销的

**Comment by lesismal** [comment]
> 固定某个连接下是只改一小部分, 生成随机数也是有开销的

压测性能没必要每次都随机，
在测试框架数据正确性时需要每个Message随机并且echo回来对比数据一致性。

压测性能使用相同数据，尽量减少其他额外开销才能尽量体现框架本身的吞吐，client side加越多额外的，就越难测高性能的server上限

**Comment by lxzan** [comment]
> deno那个websocket

开放出来给用户hack, 类似1m-websocket-server ?

**Comment by lxzan** [comment]
> > 固定某个连接下是只改一小部分, 生成随机数也是有开销的
> 
> 压测性能没必要每次都随机， 在测试框架数据正确性时需要每个Message随机并且echo回来对比数据一致性。
> 
> 压测性能使用相同数据，尽量减少其他额外开销才能尽量体现框架本身的吞吐，client side加越多额外的，就越难测高性能的server上限

随机是为了覆盖不同size的payload, 可以使用相同的随机数种子. wsbench也支持固定的payload, -f参数

**Comment by lesismal** [comment]
> 

不同框架server应该处理同一批压测数据，种子和mssage数量相同才公平，如果不同，说不定payload吞吐总量就不一致了，那当然没有对齐

**Comment by lesismal** [comment]
> 我以为客户端会受到本地端口的数量限制

四元组，server side 单个 ip+port 不变，对端单个 ip 的client 连接数就只能port限制在2字节，还得除去0或者得看内核的net.ipv4.ip_local_port_range配置。
server side 每多开一个端口，对端单个 ip 的client就可以对这个server端口来一组，一个port最多 65535，20个就130多w了，所以本地多端口测百万要方便的多，没必要docker、虚拟网络，那样又麻烦又耗更多资源。

最愁的就是本地测试，client自己消耗了大量的资源，server被挤压得难受，有条件还是多节点测试好些，让server性能也尽情释放

**Comment by lxzan** [comment]
对比了一下uWebSocket, 结果还行. 开了1C2T的虚拟机, 客户端也占了一些资源 :(

https://github.com/uNetworking/uWebSockets/tree/master/benchmarks

![image](https://github.com/lxzan/wsbench/assets/17956540/2fab1385-a0c6-43a4-b6ac-41b404de092d)

![image](https://github.com/lxzan/wsbench/assets/17956540/7ae8e793-c2bb-4594-9d6d-28c9524268e2)

**Comment by lxzan** [comment]
我应该用runtime.GoMaxProc来限制CPU的

**Comment by lxzan** [comment]
> > 我以为客户端会受到本地端口的数量限制
> 
> 四元组，server side 单个 ip+port 不变，对端单个 ip 的client 连接数就只能port限制在2字节，还得除去0或者得看内核的net.ipv4.ip_local_port_range配置。
> server side 每多开一个端口，对端单个 ip 的client就可以对这个server端口来一组，一个port最多 65535，20个就130多w了，所以本地多端口测百万要方便的多，没必要docker、虚拟网络，那样又麻烦又耗更多资源。
> 
> 最愁的就是本地测试，client自己消耗了大量的资源，server被挤压得难受，有条件还是多节点测试好些，让server性能也尽情释放

你需要一台高配电脑，听说Linus用的线程撕裂者

**Comment by lesismal** [comment]
> 你需要一台高配电脑，听说Linus用的线程撕裂者

谁也别再骗我买AMD :joy::laughing::rofl:

**Comment by lxzan** [comment]
设置 `runtime.GOMAXPROCS(2)` 之后nbio表现直线下降了

```
gws:  Duration=1.378358562s IOPS=725500 P50=210ms P90=622ms P99=855ms
nbio: Duration=4.201322279s IOPS=238020 P50=1211ms P90=2947ms P99=3900ms
```

**Comment by guonaihong** [comment]
服务端用4核机器，客户端用8核机器，足以抹平rust和golang之间的差异。用两台小机器测试，零刻那种8物理核心的16线程的小机器，32G+1TB整套下来2k。整2-3个玩玩。

**Comment by lxzan** [comment]
> 服务端用4核机器，客户端用8核机器，足以抹平rust和golang之间的差异。用两台小机器测试，零刻那种8物理核心的16线程的小机器，32G+1TB整套下来2k。整2-3个玩玩。

我平常都是用4C8T的虚拟机跑压测，测几万连接够用了

**Comment by lesismal** [comment]
这个我先关了
